name: Update Packagist

on:
  release:
    types: [published]

jobs:
  update_packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
